import { useState } from "react";

const useProcurementStatistics = () => {
  const [hasActions, _] = useState<boolean>(false);

  const columns = {
    id: "ID",
    site: "Site",
    request: "Request",
    po: "PO",
    supplier: "Supplier",
    item: "Item",
    cost_code: "CostCode",
    unit: "Unit",
    unit_price: "Unit Price",
    qty: "Qty",
    amount: "Amount",
    status: "Status",
    deliv: "Deliv.%",
    billed_percent: "Billed %",
    date_po: "Date PO",
  };
  const tableData = [
    {
      id: "1",
      site: "MAR-H",
      request: "REQ-A16-0026-CM",
      po: "PO-A16-0037-CM",
      supplier: "G2B",
      item: "MAIN DOEUVRE",
      cost_code: "CostCode",
      unit: "U",
      unit_price: "850,000.00",
      qty: "1.00",
      amount: "850,000.00",
      status: "Approved",
      deliv: "0.00%",
      billed_percent: "0.00%",
      date_po: "26-11-2024",
    },
    {
      id: "2",
      site: "MAR-H",
      request: "REQ-A16-0026-CM",
      po: "PO-A16-0037-CM",
      supplier: "G2B",
      item: "MAIN DOEUVRE",
      cost_code: "CostCode",
      unit: "U",
      unit_price: "850,000.00",
      qty: "1.00",
      amount: "850,000.00",
      status: "Approved",
      deliv: "0.00%",
      billed_percent: "0.00%",
      date_po: "26-11-2024",
    },
    {
      id: "3",
      site: "MAR-H",
      request: "REQ-A16-0026-CM",
      po: "PO-A16-0037-CM",
      supplier: "G2B",
      item: "MAIN DOEUVRE",
      cost_code: "CostCode",
      unit: "U",
      unit_price: "850,000.00",
      qty: "1.00",
      amount: "850,000.00",
      status: "Approved",
      deliv: "0.00%",
      billed_percent: "0.00%",
      date_po: "26-11-2024",
    },
    {
      id: "4",
      site: "MAR-H",
      request: "REQ-A16-0026-CM",
      po: "PO-A16-0037-CM",
      supplier: "G2B",
      item: "MAIN DOEUVRE",
      cost_code: "CostCode",
      unit: "U",
      unit_price: "850,000.00",
      qty: "1.00",
      amount: "850,000.00",
      status: "Approved",
      deliv: "0.00%",
      billed_percent: "0.00%",
      date_po: "26-11-2024",
    },
    {
      id: "5",
      site: "MAR-H",
      request: "REQ-A16-0026-CM",
      po: "PO-A16-0037-CM",
      supplier: "G2B",
      item: "MAIN DOEUVRE",
      cost_code: "CostCode",
      unit: "U",
      unit_price: "850,000.00",
      qty: "1.00",
      amount: "850,000.00",
      status: "Approved",
      deliv: "0.00%",
      billed_percent: "0.00%",
      date_po: "26-11-2024",
    },
  ];

  const inputFields: any[] = [];

  return {
    columns,
    tableData,
    inputFields,
    hasActions,
  };
};

export default useProcurementStatistics;
